#!/usr/bin/env python3
"""Generate a WBS (Work Breakdown Structure) template in Markdown with Mermaid diagram.

Usage:
    python3 scripts/generate_wbs.py \\
        --project "ECサイト構築" \\
        --phases "要件定義,基本設計,詳細設計,実装,テスト,デプロイ" \\
        --output /tmp/wbs.md

    python3 scripts/generate_wbs.py \\
        --project "ECサイト構築" \\
        --phases "Requirements,Design,Implementation,Testing,Deployment" \\
        --format csv \\
        --output /tmp/wbs.csv
"""

import argparse
import csv
import io
import sys
from pathlib import Path


def render_wbs_markdown(project: str, phases: list[str]) -> str:
    """Render WBS as Markdown with Mermaid diagram and work package table."""
    mermaid = _render_mermaid(project, phases)
    table = _render_table(phases)
    return f"""# WBS（作業分解構成図）: {project}

## WBS ツリー図

```mermaid
{mermaid}
```

## 作業パッケージ一覧

{table}

## WBS辞書テンプレート

各作業パッケージについて、以下の情報を定義してください:

| 項目 | 説明 |
|------|------|
| WBS ID | 一意の識別子（例: 1.1.1） |
| 作業パッケージ名 | タスクの正式名称 |
| 説明 | 作業内容の詳細 |
| 担当者 | 実行責任者 |
| 期間 | 見積もり工数（人日） |
| 成果物 | 完了時のアウトプット |
| 受け入れ基準 | 完了と判定する条件 |
| 依存関係 | 先行タスク・後続タスク |

---

*Generated by `project-plan-creator` skill.*
"""


def render_wbs_csv(project: str, phases: list[str]) -> str:
    """Render WBS as CSV for spreadsheet import."""
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(
        [
            "WBS ID",
            "Phase",
            "Work Package",
            "Description",
            "Owner",
            "Duration (days)",
            "Deliverable",
            "Dependencies",
        ]
    )

    for i, phase in enumerate(phases, 1):
        writer.writerow([str(i), phase, "", f"[{phase} phase]", "[TBD]", "", "", ""])
        for j in range(1, 4):
            wp_id = f"{i}.{j}"
            writer.writerow(
                [
                    wp_id,
                    phase,
                    f"[TODO: Work package {wp_id}]",
                    "[TODO: Description]",
                    "[TBD]",
                    "[TBD]",
                    "[TODO: Deliverable]",
                    _csv_dependency(i, j),
                ]
            )

    return output.getvalue()


def _render_mermaid(project: str, phases: list[str]) -> str:
    lines = ["graph TD"]
    lines.append(f"    A[{project}]")
    for i, phase in enumerate(phases, 1):
        node = chr(ord("A") + i)
        lines.append(f"    A --> {node}[{i}. {phase}]")

    lines.append("")
    for i, phase in enumerate(phases, 1):
        parent = chr(ord("A") + i)
        for j in range(1, 4):
            child = f"{parent}{j}"
            lines.append(f"    {parent} --> {child}[{i}.{j} TODO: 作業パッケージ]")

    return "\n".join(lines)


def _render_table(phases: list[str]) -> str:
    lines = [
        "| WBS ID | フェーズ | 作業パッケージ | 成果物 | 担当 | 期間 |",
        "|--------|---------|--------------|--------|------|------|",
    ]
    for i, phase in enumerate(phases, 1):
        lines.append(f"| **{i}** | **{phase}** | | | | |")
        for j in range(1, 4):
            lines.append(f"| {i}.{j} | | [TODO: 作業パッケージ] | [TODO: 成果物] | [TBD] | [TBD] |")

    return "\n".join(lines)


def _csv_dependency(phase_idx: int, wp_idx: int) -> str:
    if phase_idx == 1 and wp_idx == 1:
        return ""
    if wp_idx == 1:
        return f"{phase_idx - 1}.3"
    return f"{phase_idx}.{wp_idx - 1}"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate WBS template in Markdown (with Mermaid) or CSV")
    parser.add_argument("--project", required=True, help="Project name")
    parser.add_argument(
        "--phases",
        required=True,
        help="Comma-separated list of project phases (e.g., 'Requirements,Design,Implementation')",
    )
    parser.add_argument(
        "--format",
        default="md",
        choices=["md", "csv"],
        help="Output format: md (Markdown + Mermaid) or csv (default: md)",
    )
    parser.add_argument("--output", "-o", required=True, help="Output file path")
    args = parser.parse_args()

    phase_list = [p.strip() for p in args.phases.split(",") if p.strip()]
    if not phase_list:
        print("Error: At least one phase is required.", file=sys.stderr)
        sys.exit(1)

    if args.format == "csv":
        content = render_wbs_csv(args.project, phase_list)
    else:
        content = render_wbs_markdown(args.project, phase_list)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"WBS generated ({args.format}): {output_path}")


if __name__ == "__main__":
    main()
